name: setup
description: Setup project
runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4.0.0
      with:
        java-version: "21"
        distribution: "temurin"

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v5.0.0

    - name: Create local.properties
      run: |
        echo "CLIENT_ID=${{ secrets.CLIENT_ID }}" >> local.properties
        echo "CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}" >> local.properties