[versions]

# Project
project-plugin = "1.0.0"

# SDK versions
android-compile-sdk = "35"
android-min-sdk = "24"
android-target-sdk = "35"

# Android gradle plugin
agp = "8.6.1"

# JVM version
java = "17"

# Kotlin
kotlin = "2.1.0"

# Compose
compose-multiplatform = "1.7.3"

# KSP
ksp = "2.1.0-1.0.29" # https://github.com/google/ksp/releases

# Androidx
androidx-activity-compose = "1.10.0"
androidx-lifecycle = "2.8.4"

# Kotlinx
kotlinx-coroutines = "1.9.0" # https://github.com/Kotlin/kotlinx.coroutines/releases
kotlinx-serialization = "1.6.3" # https://github.com/Kotlin/kotlinx.serialization/releases
kotlinx-immutable-collections = "0.3.8" # https://github.com/Kotlin/kotlinx.collections.immutable/releases
kotlinx-datetime = "0.6.1" # https://github.com/Kotlin/kotlinx-datetime/releases

# Detekt
detekt = "1.23.7" # https://github.com/detekt/detekt/releases
detekt-compose = "0.0.26" # https://github.com/twitter/compose-rules/releases

# Koin
koin-bom = "3.5.1" # https://github.com/InsertKoinIO/koin/releases

# Ktor
ktor = "2.3.6" # https://github.com/ktorio/ktor/releases

# Decompose
decompose = "3.0.0" # https://github.com/arkivanov/Decompose/releases

# Essenty
essenty = "2.0.0" # https://github.com/arkivanov/Essenty/releases

# MVI Kotlin
mvikotlin = "4.0.0" # https://github.com/arkivanov/MVIKotlin/releases

# KVault
kvault = "1.12.0" # https://github.com/Liftric/KVault/releases

# Coil
coil = "2.5.0" # https://github.com/coil-kt/coil/releases

[libraries]

# Kotlin
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test-common = {module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin"}
kotlin-test-annotations-common = {module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin"}
kotlin-test-junit = {module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin"}

# Android
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }

# Androidx
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }

# Kotlinx
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutable-collections" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

# Compose
compose-compiler-gradle = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
compose-multiplatform-gradle = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }

# Detekt
detekt-gradle = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-compose = { module = "com.twitter.compose.rules:detekt", version.ref = "detekt-compose" }

# Koin
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-test = { module = "io.insert-koin:koin-test" }

# Ktor
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Decompose - https://github.com/arkivanov/Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-extensions-compose = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }
decompose-extensions-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose" }

# Essenty - https://github.com/arkivanov/Essenty
essenty = { module = "com.arkivanov.essenty:lifecycle", version.ref = "essenty" }

# MVI Kotlin
mvikotlin = { module = "com.arkivanov.mvikotlin:mvikotlin", version.ref = "mvikotlin" }
mvikotlin-main = { module = "com.arkivanov.mvikotlin:mvikotlin-main", version.ref = "mvikotlin" }
mvikotlin-logging = { module = "com.arkivanov.mvikotlin:mvikotlin-logging", version.ref = "mvikotlin" }
mvikotlin-timetravel = { module = "com.arkivanov.mvikotlin:mvikotlin-timetravel", version.ref = "mvikotlin" }
mvikotlin-extensions-coroutines = { module = "com.arkivanov.mvikotlin:mvikotlin-extensions-coroutines", version.ref = "mvikotlin" }

# KVault
kvault = { module = "com.liftric:kvault", version.ref = "kvault" }

# Coil - https://github.com/coil-kt/coil
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[bundles]

mvikotlin = ["mvikotlin", "mvikotlin-main", "mvikotlin-logging", "mvikotlin-timetravel", "mvikotlin-extensions-coroutines"]
coil = ["coil", "coil-compose"]

[plugins]

# Android
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }

# KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Kotlin
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

# Kotlinx
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Compose
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }

# Project
project-multiplatform = { id = "project.multiplatform.plugin", version.ref = "project-plugin" }
project-compose = { id = "project.compose.plugin", version.ref = "project-plugin" }
project-serialization = { id = "project.serialization.plugin", version.ref = "project-plugin" }
project-coroutines = { id = "project.coroutines.plugin", version.ref = "project-plugin" }
project-koin = { id = "project.koin.plugin", version.ref = "project-plugin" }
project-ktor = { id = "project.ktor.plugin", version.ref = "project-plugin" }