name: Build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4096M -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true -Dorg.gradle.configuration-cache=true -Dorg.gradle.caching=true"

jobs:
  detekt:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Run static code analysis
        run: ./gradlew detekt --continue

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Run unit tests
        run: ./gradlew unitTest :android:app:test

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: "**/build/reports/tests/"

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Build Android debug APK
        run: ./gradlew :android:app:assembleDebug

  ui-test-build-ios:
    name: UI tests + Build iOS
    runs-on: macos-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}

      - name: Run Compose UI tests
        run: ./gradlew uiTest

      - name: Upload UI test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-reports
          path: "**/build/reports/tests/"

      - name: Build iOS simulator app
        run: |
          xcodebuild build \
          -project ios/app.xcodeproj \
          -configuration Debug \
          -scheme prodDebug \
          -sdk iphonesimulator \
          -derivedDataPath ./build \
          EXCLUDED_ARCHS="x86_64" \
          -verbose
