name: Setup local.properties
description: Generates local.properties with client credentials

inputs:
  client-id:
    required: true
    description: Client ID
  client-secret:
    required: true
    description: Client Secret

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "CLIENT_ID=${{ inputs.client-id }}" >> local.properties
        echo "CLIENT_SECRET=${{ inputs.client-secret }}" >> local.properties